[package]
name = "law_enforcement"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "leb"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.24", features = ["macros", "rt-multi-thread"] }
serenity = { default-features = false, features = ["client", "gateway", "model", "rustls_backend"], version = "0.11"}
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5"
structstruck = "0.3.0"
lazy_static = "1.4"
log = "0.4.6"
env_logger = "0.10.0"
leb_warn = { git = "https://github.com/El-Wumbus/LEB-Warn.git" }
