enum_discrim_align_threshold = 20
format_code_in_doc_comments = true
blank_lines_upper_bound = 2 
force_multiline_blocks = true
# control_brace_style = "AlwaysNextLine"
hex_literal_case = "Upper"
reorder_imports = true
fn_single_line = true
format_strings = true
wrap_comments = true
indent_style = "Block"
brace_style = "AlwaysNextLine"